# Generated by Django 6.1 on 2026-08-25 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(help_text='Короткая подпись, например «Модуль 01 · Математика»', max_length=100)),
                ('intro', models.TextField(help_text='Один-два вводных предложения под заголовком модуля')),
                ('accent', models.CharField(choices=[('math', 'Математика'), ('eng', 'English'), ('info', 'Информатика'), ('opt', 'Спецпрактикум')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_label', models.CharField(blank=True, help_text='Заголовок подгруппы заданий, например «A. Вставьте is / are» (необязательно)', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('prompt', models.TextField(help_text='Текст задания')),
                ('answer', models.TextField(blank=True, help_text='Ответ для самопроверки; пусто — задание открытое (например, код)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='handbook.module')),
            ],
            options={
                'ordering': ['module', 'order'],
            },
        ),
    ]
